#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lp1,            sensorTouch)
#pragma config(Sensor, dgtl2,  lp2,            sensorTouch)
#pragma config(Sensor, dgtl3,  quad1,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lq1,            sensorTouch)
#pragma config(Sensor, dgtl6,  lq2,            sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "uart_comms.c"

void ReadSensors()
{
  /** MODIFY THIS FUNCTION TO READ SENSORS **/
  // Example: SerialWriteSensor(quad1);
	SerialWriteSensor(pot1);
	SerialWriteSensor(lp1);
	SerialWriteSensor(lp2);
	SerialWriteSensor(quad1);
	SerialWriteSensor(lq1);
	SerialWriteSensor(lq2);
}

void RunMotors(int *mtrV)
{
  motor[port1]  = mtrV[0];
  motor[port2]  = mtrV[1];
  motor[port3]  = mtrV[2];
  motor[port4]  = mtrV[3];
  motor[port5]  = mtrV[4];
  motor[port6]  = mtrV[5];
  motor[port7]  = mtrV[6];
  motor[port8]  = mtrV[7];
  motor[port9]  = mtrV[8];
  motor[port10] = mtrV[9];
}

task serialCommsTask()
{
  setTaskPriority(serialCommsTask, 20); // bump our priority
  while (true) {
    SerialUpdate();
    wait1Msec(2); // comms task expects to be run every 2mS
  }
}

task main()
{
  if (SerialInit(UART1, baudRate115200)) {
    startTask(serialCommsTask);
  }

  while (true) {
    // nothing to do here, event-based handling by other tasks
    wait1Msec(100);
  }
}
