#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "uart_comms.c"

static int motorValues[10];

void ReadSensors()
{
  /** MODIFY THIS FUNCTION TO READ SENSORS **/
  // Example: SerialWriteSensor(quad1);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[0] + 0x7F);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[1] + 0x7F);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[2] + 0x7F);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[3] + 0x7F);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[4] + 0x7F);
  UARTWriteSensorValue(sensorQuadEncoder,   motorValues[5] + 0x7F);

  UARTWriteSensorValue(sensorPotentiometer, motorValues[6] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[7] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[8] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[9] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[0] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[0] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[0] + 0x7F);
  UARTWriteSensorValue(sensorPotentiometer, motorValues[0] + 0x7F);
}

void RunMotors(int *mtrV)
{
  int i;
  for (i = 0; i < 10; i++) {
    motorValues[i] = mtrV[i];
  }

  motor[port1]  = mtrV[0];
  motor[port2]  = mtrV[1];
  motor[port3]  = mtrV[2];
  motor[port4]  = mtrV[3];
  motor[port5]  = mtrV[4];
  motor[port6]  = mtrV[5];
  motor[port7]  = mtrV[6];
  motor[port8]  = mtrV[7];
  motor[port9]  = mtrV[8];
  motor[port10] = mtrV[9];
}

task serialCommsTask()
{
  setTaskPriority(serialCommsTask, 20); // bump our priority
  while (true) {
    SerialUpdate();
    wait1Msec(2); // comms task expects to be run every 2mS
  }
}

task main()
{
  if (SerialInit(UART1, baudRate115200)) {
    startTask(serialCommsTask);
  }

  while (true) {
    // nothing to do here, event-based handling by other tasks
    wait1Msec(100);
  }
}
