#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  quad,           sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "uart_comms.c"

void ReadSensors()
{
  /** MODIFY THIS FUNCTION TO READ SENSORS **/
  // Example: SerialWriteSensor(quad1);
	SerialWriteSensor(quad);
}

void RunMotors(int *val)
{
  motor[port1]  = val[0];
  motor[port2]  = val[1];
  motor[port3]  = val[2];
  motor[port4]  = val[3];
  motor[port5]  = val[4];
  motor[port6]  = val[5];
  motor[port7]  = val[6];
  motor[port8]  = val[7];
  motor[port9]  = val[8];
  motor[port10] = val[9];
}

static char buf[128];
char c = 'A';

task serialCommsTask()
{
  setTaskPriority(serialCommsTask, 20); // bump our priority
  while (true) {
  	sprintf(buf, "Large character buffer (256 max), baudrate115200, 2ms delay per loop: %c\n", c);
    c++;
    if (c > 'Z') {
    	c = 'A';
    }
    // SerialUpdate();
    RobotC_WriteBuf(UART1, buf, strlen(buf));
    //wait1Msec(5); // works at 10
    wait1Msec(2); // comms task expects to be run every 2mS
  }
}

task main()
{
  if (SerialInit(UART1, baudRate115200, "U1")) {
    startTask(serialCommsTask);
  }

  while (true) {
    // nothing to do here, event-based handling by other tasks
    wait1Msec(100);
  }
}
